will = None
background = {}
grass = None
monsters = []
break_objects = []
Endtree =[]

grasslevel =0
grass_level=0
slime_count =0
golem_count =5
Hanari_count=0
sword_count =1
tree_count =0
rich = 10
HP=80
willx,willy =200,300
clampx =150
clampy =100
door_state={"up":False,"down" :False,"right":True,"left":False}